"""Добавил моделя для записи логов по работе с БД. Установил связь с моделью User с каскадным удалением записей

Revision ID: ef2c3c781b64
Revises: 6a7dad382601
Create Date: 2023-12-10 14:38:56.084785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2c3c781b64'
down_revision: Union[str, None] = '6a7dad382601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_action_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_action_log_id'), 'db_action_log', ['id'], unique=True)
    op.create_index(op.f('ix_db_action_log_message'), 'db_action_log', ['message'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_action_log_message'), table_name='db_action_log')
    op.drop_index(op.f('ix_db_action_log_id'), table_name='db_action_log')
    op.drop_table('db_action_log')
    # ### end Alembic commands ###
